<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Complete Purchase</name>
   <tag></tag>
   <elementGuidId>2b1c2d94-681d-453d-957d-22462a4f7fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56e412eb-1371-45c0-bec1-8afc4cccc866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-12-9 CheckoutButton_noMargin_mv-3h</value>
      <webElementGuid>2b02b1c7-c4ac-4d4e-b1a3-95e9ee04fad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-submit-btn</value>
      <webElementGuid>7d5a190f-3105-468a-97c8-5634c8f273b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-button-initial</value>
      <webElementGuid>a4082c7c-b9aa-4348-aec7-4c059e1fbe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3e0317a-883e-441f-a5b0-bbe217e5f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete Purchase</value>
      <webElementGuid>c221a47a-3911-48c0-b5ea-d86413b62612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-submit-btn&quot;)</value>
      <webElementGuid>7d1b148b-a3c7-4d78-ad9c-a5c1b75098a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-submit-btn']</value>
      <webElementGuid>afe84e83-03aa-404a-a86f-1dfccceb27fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hermione-container']/div/main/div[4]/div[2]/button</value>
      <webElementGuid>6a15aca1-3a4a-42c7-8d97-2e0c11837a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay over time for eligible purchases of $199.00-$10,000.00. Not available for this transaction.'])[1]/following::button[1]</value>
      <webElementGuid>3be5a0e4-6018-4971-862a-e66f8577b436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Monthly'])[1]/following::button[1]</value>
      <webElementGuid>26dc1f3c-a77b-469c-9e8c-fcbbdaea77e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment method rights'])[1]/preceding::button[1]</value>
      <webElementGuid>da248310-a4f3-4102-a7ba-cce44e6ca11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Cancel and return to John Doe', &quot;'&quot;, 's Test Store')])[1]/preceding::button[1]</value>
      <webElementGuid>ccfab600-9059-4d10-a081-b704998a25f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complete Purchase']/parent::*</value>
      <webElementGuid>09eb481a-1d9f-4ca4-898a-a4ecd41e3824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>2bc97632-be90-4822-a338-2cda388990ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-submit-btn' and (text() = 'Complete Purchase' or . = 'Complete Purchase')]</value>
      <webElementGuid>93d1057f-5b2a-404b-8283-d806dce26886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
